version: "3"
services:
  tor:
    build: tor/
    restart: unless-stopped
    expose:
      - 9051
    networks:
      - net_isolated
      - net_control
      - net_external
    volumes:
      - torrc:/etc/tor/
      - authcookie:/var/lib/tor/
      - /etc/localtime:/etc/localtime:ro

  nyx:
    build: nyx/
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - tor
    networks:
      - net_control
    volumes:
      - torrc:/etc/tor/
      - authcookie:/var/lib/tor/
      - /etc/localtime:/etc/localtime:ro

  webserver:
    build: webserver/
    restart: unless-stopped
    expose:
      - 4000
    depends_on:
      - tor
    networks:
      - net_isolated
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  torrc: {}
  authcookie: {}

networks:
  net_isolated:
    internal: true
  net_control:
    internal: true
  net_external:
